# In future could be useful to separate different constants fro prod., dev., staging... etc.

server:
  HOST: '0.0.0.0'
  PORT: '5000'

postgres:
  DB_NAME: 'bakingbread'
  DB_PASSWORD: 'test3915'