# In future could be useful to separate different constants for prod., dev., staging... etc.

server:
  HOST: '0.0.0.0'
  PORT: '5000'

postgres:
  DB_NAME: 'bakingbread'
  DB_PASSWORD: 'test3915'

github:
  token: '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'